----------------------------------------------------
--CREACIÓN DE TABLA PROCEDIMIENTOS EN BASE DE DATOS
----------------------------------------------------
GO
--CREACIÓN DE UN STORED PROCEDURE PARA CONSULTAR LAS PERSONAS CREADAS
CREATE PROCEDURE ConsultarPersonas
AS
BEGIN
    SELECT * FROM EntidadPersonas;
END

GO
--CREACIÓN DE UN STORED PROCEDURE PARA CONSULTAR LAS PERSONAS CREADAS POR PAISES
CREATE PROCEDURE ConsultarPorPaises
AS
BEGIN
    SELECT * FROM EntidadPersonas WHERE Pais LIKE '%Colombia%';
END

GO
--CREACIÓN DE UN STORED PROCEDURE PARA CONSULTAR LAS PERSONAS CREADAS POR DEPARTAMENTO
CREATE PROCEDURE ConsultarPorDepartamento
AS
BEGIN
    SELECT * FROM EntidadPersonas WHERE Pais LIKE '%Risaralda%';
END

GO
--CREACIÓN DE UN STORED PROCEDURE PARA CONSULTAR LAS PERSONAS CREADAS POR MUNICIPIO
CREATE PROCEDURE ConsultarPorMunicipio
AS
BEGIN
    SELECT * FROM EntidadPersonas WHERE Pais LIKE '%Pereira%';
END